AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Owner:
    Description: "Owner name for taggin"
    Type: String
    Default: "Unidentified"

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      #BucketName: !Ref BucketName
      Tags:
        -
          Key: "Owner"
          Value: !Ref Owner

Outputs:
  S3BucketSecureURL:
    Value: !Join 
      - ''
      - - 'https://'
        - !GetAtt 
          - S3Bucket
          - DomainName
    Description: Name of S3 bucket to hold website content
